# see http://gohugo.io/overview/configuration/
baseurl = "https://kohkimakimoto.github.io/essh/"
disableHugoGeneratorInject = true
disableKinds = ["RSS"]
languageCode = "en-us"
title = "Essh - Extended ssh command"
uglyURLs = true
